
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-08
owner: ucsb-cs156-f25
repo_name: team01-f25-08
pull_requests: [{"author":{"id":"U_kgDOC7SI0A","is_bot":false,"login":"sriya-vollala","name":""},"headRefName":"sriya-vollala-put-for-recrequests","number":68,"title":"added the put function","url":"https://github.com/ucsb-cs156-f25/team01-f25-08/pull/68"}]
