
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-08
owner: ucsb-cs156-f25
repo_name: team01-f25-08
pull_requests: [{"author":{"id":"U_kgDOCVHSlQ","is_bot":false,"login":"DengLucy","name":""},"headRefName":"DengLucy-UCSBOrganization-controller","number":46,"title":"DengLucy Create UCSBOrganization Controller","url":"https://github.com/ucsb-cs156-f25/team01-f25-08/pull/46"},{"author":{"id":"U_kgDOCVHSlQ","is_bot":false,"login":"DengLucy","name":""},"headRefName":"DengLucy-UCSBOrganization-create-db","number":45,"title":"PC- create database table for UCSBOrganization","url":"https://github.com/ucsb-cs156-f25/team01-f25-08/pull/45"},{"author":{"id":"U_kgDOCeK9Ng","is_bot":false,"login":"krystelleb22","name":""},"headRefName":"Krystelle-MenuItemReview","number":44,"title":"kb - create database table for MenuItemReviews","url":"https://github.com/ucsb-cs156-f25/team01-f25-08/pull/44"},{"author":{"id":"MDQ6VXNlcjE1OTcwNTcw","is_bot":false,"login":"dalidog","name":"Dalia Sebat"},"headRefName":"Dalia-Articles","number":43,"title":"Added Articles database","url":"https://github.com/ucsb-cs156-f25/team01-f25-08/pull/43"}]
